# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
require 'rubygems'
require 'bundler/setup'

require 'permissify'
require 'permissify/ability_class'

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
end

class Ability
  class << self
    include Permissify::AbilityClass
    
    def seed
      add_category('Tabs', 'Tabs', ['Role'], %w(Admin Dealer Corporate Brand Merchant))
      { 'Roles'                 => 'Admin',
        'Admin Users'           => 'Admin',
        'Dealer Users'          => 'Dealer Admin',
        'Corporate Users'       => 'Corporate Admin',
        'Brand Users'           => 'Brand Admin',
        'Merchant Users'        => 'Merchant Admin',
      }.each{ |category, section| add_category(category, section) }
    end
  end
end

class NoSeedAbility
  class << self
    include Permissify::AbilityClass
  end
end
